services:
  user:
    build:
      context: .
      dockerfile: ./build/user/Dockerfile
    container_name: user-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:50051"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s


  protoc:
    build:
      context: .
      dockerfile: ./build/protoc/Dockerfile
    volumes:
      - .:/work
    command: /bin/sh -c "protoc --go_out=. --go-grpc_out=. ./proto/*.proto"