services:
  user:
    build:
      context: .
      dockerfile: ./build/user/Dockerfile
    container_name: user-server
    restart: always
    depends_on:
      - db
    ports:
      - "50051:50051"

  db:
    image: mysql:8.0
    container_name: user-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  protoc:
    build:
      context: .
      dockerfile: ./build/protoc/Dockerfile
    volumes:
      - .:/work
    command: /bin/sh -c "protoc --go_out=. --go-grpc_out=. ./proto/*.proto"